# Generated by Django 5.1.7 on 2025-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
